const IMG=i=>`https://the-brass-pads.grok.me/listings/${String(i).padStart(2,"0")}.jpg`;
const CITIES={"Akron, OH":[41.0814,-81.519],"Cleveland, OH":[41.4993,-81.6944],"Columbus, OH":[39.9612,-82.9988],"Cincinnati, OH":[39.1031,-84.512],"Pittsburgh, PA":[40.4406,-79.9959],"Youngstown, OH":[41.0998,-80.6495],"Hermitage, PA":[41.2334,-80.4487],"Detroit, MI":[42.3314,-83.0458],"Chicago, IL":[41.8781,-87.6298],"Atlanta, GA":[33.749,-84.388],"Dallas, TX":[32.7767,-96.797],"Austin, TX":[30.2672,-97.7431],"Nashville, TN":[36.1627,-86.7816],"Denver, CO":[39.7392,-104.9903],"Miami, FL":[25.7617,-80.1918],"New York, NY":[40.7128,-74.006],"Los Angeles, CA":[34.0522,-118.2437]};
const HOODS={"Akron, OH":["Goodyear Heights","Ellet","Portage Lakes","Kenmore","Highland Square","Merriman Valley","North Hill","Wallhaven","West Akron","Downtown","Firestone Park","Cascade Valley"],"Pittsburgh, PA":["Lawrenceville","Bloomfield","South Side","Shadyside","East Liberty","Strip District"],"Hermitage, PA":["Downtown","Hickory","State Street","Buhl Park"]};
const NAMES=["Chris Khan","Maya Ortiz","Leon Brooks","Priya Shah","Dana Wells","Omar Reid"];
const $=id=>document.getElementById(id);
const store={get(k,d){try{return JSON.parse(localStorage.getItem("bp3-"+k))??d}catch{return d}},set(k,v){localStorage.setItem("bp3-"+k,JSON.stringify(v))}};
function seed(str){let h=0;for(const c of str)h=c.charCodeAt(0)+((h<<5)-h);return Math.abs(h)}
function money(n){return "$"+Math.round(n).toLocaleString()}
function dealScore(price,sqft,med){return Math.max(12,Math.min(98,Math.round(100-(price/med)*50-(price/sqft)*8)))}
function dealClass(s){return s>=70?"deal":s>=50?"deal mid":"deal high"}
function dealLabel(s){return s>=70?`Deal ${s}`:s>=50?`Fair ${s}`:`High ${s}`}
function makeCity(city,intent){const [lat0,lng0]=CITIES[city]||[41.08,-81.52];const n=city==="Akron, OH"?36:16+(seed(city)%8);const hoods=HOODS[city]||["Downtown","Westside","East End","Lakeside","Midtown","Parkview"];const med=intent==="buy"?180000+(seed(city)%220000):900+(seed(city)%1100);const pads=[];for(let i=0;i<n;i++){const s=seed(city+intent+i);const type=s%4===0?"house":"apartment";const beds=type==="house"?2+(s%3):s%5===0?0:1+(s%3);const baths=beds===0?1:Math.max(1,+(beds*0.7+(s%2)*0.5).toFixed(1));const sqft=beds===0?400+(s%120):550+beds*220+(s%180);const price=intent==="buy"?Math.round((140000+beds*42000+(s%90000)+sqft*40)/1000)*1000:Math.round((490+(type==="house"?330:0)+beds*180+(s%380))/5)*5;const pets=s%3!==0;const day=4+(s%24);pads.push({id:intent+"-"+city+"-"+i,city,intent,type,beds,baths,sqft,price,pets,hood:hoods[s%hoods.length],img:IMG((s%23)+1),deposit:intent==="buy"?Math.round(price*0.03):Math.round(price*(s%3===0?1:0.5)/5)*5,title:beds===0?"Bright studio with tall windows":(type==="house"?"Quiet house near the park":"Updated apartment, good light"),amenities:["Updated kitchen","Balcony","Dishwasher","In-unit laundry","Parking","AC","Yard","Fireplace"].filter((_,k)=>(s>>k)&1).slice(0,4),manager:NAMES[s%NAMES.length],lease:intent==="buy"?"For sale":"12-month, then monthly",avail:`2026-10-${String(day).padStart(2,"0")}`,desc:`${beds===0?"Studio":beds+" bed"} ${type} in ${hoods[s%hoods.length]}. ${sqft.toLocaleString()} ft².`,lat:lat0+((s%80)-40)/900,lng:lng0+((Math.floor(s/7)%80)-40)/900,med,score:dealScore(price,sqft,med)})}return pads.sort((a,b)=>a.price-b.price)}
const CACHE={};
function padsFor(city,intent){const k=city+"|"+intent;if(!CACHE[k])CACHE[k]=makeCity(city,intent);return CACHE[k]}
function allUserPads(){return store.get("listed",[])}
function findPad(id){const mine=allUserPads().find(p=>p.id===id);if(mine)return mine;for(const city of Object.keys(CITIES)){for(const intent of ["rent","buy"]){const p=padsFor(city,intent).find(x=>x.id===id);if(p)return p}}}
const queryCity=new URLSearchParams(location.search).get("city");
const initialCity=Object.keys(CITIES).find(c=>c.toLowerCase()===String(queryCity||"").toLowerCase())||"Akron, OH";
const state={tab:"search",city:initialCity,intent:"rent",type:"all",beds:"any",pets:false,max:8000,sort:"price",saved:new Set(store.get("saved",[])),inbox:store.get("inbox",[]),apps:store.get("apps",[]),tours:store.get("tours",[]),profile:store.get("profile",{name:"Guest",email:"",phone:"",income:52000,credit:"good"})};
$("q").value=state.city;
Object.keys(CITIES).forEach(c=>{const o=document.createElement("option");o.value=c;$("citylist").appendChild(o)});
$("cityChips").innerHTML=Object.keys(CITIES).slice(0,11).map(c=>`<button class="chip${c===state.city?" on":""}" data-city="${c}">${c}</button>`).join("");
function toast(t){const el=$("toast");el.textContent=t;el.style.display="block";setTimeout(()=>el.style.display="none",1700)}
function persistSaved(){store.set("saved",[...state.saved])}
function addInbox(item){state.inbox.unshift({id:"m"+Date.now(),time:new Date().toISOString(),...item});store.set("inbox",state.inbox)}
function filtered(){const extra=allUserPads().filter(p=>p.city===state.city&&p.intent===state.intent);let list=[...extra,...padsFor(state.city,state.intent)];if(state.type!=="all")list=list.filter(p=>p.type===state.type);if(state.beds==="0")list=list.filter(p=>p.beds===0);else if(state.beds==="3")list=list.filter(p=>p.beds>=3);else if(state.beds!=="any")list=list.filter(p=>p.beds===+state.beds);if(state.pets)list=list.filter(p=>p.pets);list=list.filter(p=>p.price<=state.max);const sorters={price:(a,b)=>a.price-b.price,sqft:(a,b)=>(a.price/a.sqft)-(b.price/b.sqft),soon:(a,b)=>a.avail.localeCompare(b.avail),deal:(a,b)=>b.score-a.score};return list.sort(sorters[state.sort])}
function cardHTML(p){const unit=p.intent==="buy"?"":"<span>/mo</span>";return `<article class="card" data-id="${p.id}"><img src="${p.img}" alt="" /><span class="badge">${p.intent==="buy"?"FOR SALE":p.type.toUpperCase()}</span><button class="save${state.saved.has(p.id)?" on":""}" data-save="${p.id}" type="button">${state.saved.has(p.id)?"♥":"♡"}</button><div class="info"><div class="price">${money(p.price)}${unit}</div><small>${p.beds===0?"Studio":p.beds+" bed"} · ${p.baths} ba · ${p.sqft.toLocaleString()} ft²</small><small>${p.hood}, ${p.city.split(",")[0]}</small><span class="${dealClass(p.score)}">${dealLabel(p.score)} · ${money(p.price/p.sqft)}${p.intent==="buy"?"":"/ft²"}</span></div></article>`}
function renderSearch(){const list=filtered();const min=list[0]?.price;$("heroSub").textContent=state.intent==="buy"?"Buy a pad. Offer, tour, and message the seller in-app.":"Search, tour, apply, message, list — all inside BrassPad.";document.querySelector(".hero").textContent=state.intent==="buy"?"Pads for sale, low note to high.":"Pads for rent, low note to high.";$("meta").textContent=list.length?`${list.length} pads in ${state.city} · ${$("sort").selectedOptions[0].text.toLowerCase()}${min?` · from ${money(min)}`:""}`:"No pads match.";$("grid").innerHTML=list.length?list.map(cardHTML).join(""):`<p class="empty">Nothing in that range.</p>`}
function renderSaved(){const list=[...state.saved].map(findPad).filter(Boolean);$("savedGrid").innerHTML=list.length?list.map(cardHTML).join(""):`<p class="empty">Heart a pad to keep it.</p>`}
function renderInbox(){$("inboxList").innerHTML=state.inbox.length?state.inbox.map(m=>`<div class="item" data-thread="${m.padId||""}"><div><h4>${m.title}</h4><div class="muted">${m.body}</div></div><span class="muted">${(m.time||"").slice(5,10)}</span></div>`).join(""):`<p class="empty">No messages yet. Open a pad and tap Send.</p>`}
function renderMe(){$("meLine").textContent=`${state.profile.name} · ${state.profile.email}`;$("appCount").textContent=state.apps.length;$("tourCount").textContent=state.tours.length;$("listCount").textContent=allUserPads().length;$("saveCount").textContent=state.saved.size;$("myList").innerHTML=allUserPads().length?allUserPads().map(p=>`<div class="item"><div><h4>${p.title}</h4><div class="muted">${money(p.price)} · ${p.city}</div></div><button class="ghost" data-id="${p.id}">Open</button></div>`).join(""):`<p class="muted">None yet.</p>`;$("myApps").innerHTML=state.apps.length?state.apps.map(a=>`<div class="item"><div><h4>${a.padTitle}</h4><div class="muted">${a.status} · ${a.city}</div></div></div>`).join(""):`<p class="muted">None yet.</p>`}
let map,markers;
function renderMap(){const list=filtered();const [lat,lng]=CITIES[state.city]||[41.08,-81.52];if(!map){map=L.map("map");L.tileLayer("https://{s}.basemaps.cartocdn.com/dark_all/{z}/{x}/{y}{r}.png",{attribution:"© OSM © CARTO"}).addTo(map);markers=L.layerGroup().addTo(map)}setTimeout(()=>map.invalidateSize(),80);map.setView([lat,lng],12);markers.clearLayers();list.forEach(p=>{const pin=L.circleMarker([p.lat,p.lng],{radius:8,color:"#d4b483",fillColor:"#d4b483",fillOpacity:.9,weight:1});pin.bindPopup(`<b>${money(p.price)}</b><br>${p.hood}<br><button data-id="${p.id}">Open</button>`);pin.addTo(markers)})}
function showTab(tab){state.tab=tab;["search","map","saved","inbox","me"].forEach(t=>{$("pg-"+t).classList.toggle("hidden",t!==tab);document.querySelector(`[data-tab="${t}"]`).classList.toggle("on",t===tab)});if(tab==="search")renderSearch();if(tab==="saved")renderSaved();if(tab==="inbox")renderInbox();if(tab==="me")renderMe();if(tab==="map")renderMap()}
function openPad(id){const p=findPad(id);if(!p)return;const unit=p.intent==="buy"?"":" /mo";$("dlg").innerHTML=`<div class="sheet"><button class="close" id="x">✕</button><img class="hero" src="${p.img}" alt="" /><div class="body"><div class="price">${money(p.price)}<span>${unit}</span></div><h3 style="margin:8px 0 4px">${p.title}</h3><p class="muted">${p.beds===0?"Studio":p.beds+" bed"} · ${p.baths} bath · ${p.sqft.toLocaleString()} ft² · ${p.type}</p><p>${p.hood}, ${p.city}</p><p style="margin-top:10px">${p.desc} ${p.lease}. Available ${p.avail}.</p><div class="facts"><div class="fact"><b>Available</b>${p.avail}</div><div class="fact"><b>${p.intent==="buy"?"Down ~3%":"Deposit"}</b>${money(p.deposit)}</div><div class="fact"><b>Pets</b>${p.pets?"Small pets ok":"No pets"}</div><div class="fact"><b>Deal</b>${dealLabel(p.score)}</div></div><div class="tags">${p.amenities.map(a=>`<span class="tag">${a}</span>`).join("")}</div><h4>Contact ${p.intent==="buy"?"seller":"manager"}</h4><p class="muted">${p.manager} · replies in-app</p><label>Message</label><textarea id="ms">Hi ${p.manager.split(" ")[0]}, I want to see the ${p.type} in ${p.hood}.</textarea><div class="actions"><button class="go" id="send">Send</button><button class="ghost" id="tour">Tour</button>${p.intent==="rent"?`<button class="ghost" id="apply">Apply</button>`:`<button class="ghost" id="offer">Offer</button>`}<button class="ghost" data-save="${p.id}">${state.saved.has(p.id)?"Saved":"Save"}</button><a class="ghost" href="https://vesper-mu-ecru.vercel.app" target="_blank" rel="noreferrer" style="text-decoration:none">Find work ↗</a></div></div></div>`;$("dlg").showModal();$("x").onclick=()=>$("dlg").close();$("send").onclick=()=>{addInbox({title:p.manager,body:$("ms").value,padId:p.id,kind:"msg"});$("dlg").close();toast("Sent in BrassPad.")};$("tour").onclick=()=>openTour(p);const apply=$("apply");if(apply)apply.onclick=()=>openApply(p);const offer=$("offer");if(offer)offer.onclick=()=>openOffer(p)}
function openTour(p){$("dlg").innerHTML=`<div class="sheet"><div class="body"><button class="close" id="x">✕</button><h3>Request a tour</h3><p class="muted">${p.title} · ${p.hood}</p><label>Date</label><input class="field" id="td" type="date" value="2026-10-20" /><label>Time</label><select id="tt"><option>10:00 AM</option><option>12:00 PM</option><option>4:00 PM</option><option>6:00 PM</option></select><div class="actions"><button class="go" id="ok">Book tour</button></div></div></div>`;$("dlg").showModal();$("x").onclick=()=>$("dlg").close();$("ok").onclick=()=>{const when=$("td").value+" "+$("tt").value;state.tours.push({padId:p.id,when,title:p.title});store.set("tours",state.tours);addInbox({title:"Tour confirmed",body:`${p.hood} · ${when}`,padId:p.id,kind:"tour"});$("dlg").close();toast("Tour booked.")}}
function openApply(p){const pr=state.profile;$("dlg").innerHTML=`<div class="sheet"><div class="body"><button class="close" id="x">✕</button><h3>Apply in-app</h3><p class="muted">One form. Reuse next time.</p><label>Name</label><input class="field" id="an" value="${pr.name}" /><label>Email</label><input class="field" id="ae" value="${pr.email}" /><label>Phone</label><input class="field" id="ap" value="${pr.phone}" /><label>Yearly income</label><input class="field" id="ai" type="number" value="${pr.income}" /><label>Credit</label><select id="ac"><option ${pr.credit==="good"?"selected":""}>good</option><option>fair</option><option>building</option></select><label>Move-in</label><input class="field" id="am" type="date" value="${p.avail}" /><div class="actions"><button class="go" id="ok">Submit application</button></div></div></div>`;$("dlg").showModal();$("x").onclick=()=>$("dlg").close();$("ok").onclick=()=>{state.profile={name:$("an").value,email:$("ae").value,phone:$("ap").value,income:+$("ai").value,credit:$("ac").value};store.set("profile",state.profile);const app={id:"a"+Date.now(),padId:p.id,padTitle:p.title,city:p.city,status:"In review"};state.apps.unshift(app);store.set("apps",state.apps);addInbox({title:"Application sent",body:`${p.title} · In review`,padId:p.id,kind:"app"});$("dlg").close();toast("Application sent.")}}
function openOffer(p){$("dlg").innerHTML=`<div class="sheet"><div class="body"><button class="close" id="x">✕</button><h3>Make an offer</h3><p class="muted">Listed ${money(p.price)}</p><label>Your offer</label><input class="field" id="of" type="number" value="${p.price}" /><label>Earnest money</label><input class="field" id="em" type="number" value="${Math.round(p.price*0.01)}" /><div class="actions"><button class="go" id="ok">Send offer</button></div></div></div>`;$("dlg").showModal();$("x").onclick=()=>$("dlg").close();$("ok").onclick=()=>{addInbox({title:"Offer sent",body:`${money(+$("of").value)} on ${p.title}`,padId:p.id,kind:"offer"});$("dlg").close();toast("Offer sent.")}}
function openList(){$("dlg").innerHTML=`<div class="sheet"><div class="body"><button class="close" id="x">✕</button><h3>List a pad</h3><label>City</label><input class="field" id="lc" value="${state.city}" /><label>Neighborhood</label><input class="field" id="lh" value="Downtown" /><label>Type</label><select id="lt"><option value="apartment">Apartment</option><option value="house">House</option></select><div class="cal"><div><label>Beds</label><input class="field" id="lb" type="number" value="2" /></div><div><label>Baths</label><input class="field" id="lba" type="number" value="1" step=".5" /></div></div><div class="cal"><div><label>Sq ft</label><input class="field" id="ls" type="number" value="900" /></div><div><label>Price</label><input class="field" id="lp" type="number" value="${state.intent==="buy"?220000:950}" /></div></div><label>Title</label><input class="field" id="ln" value="My pad" /><div class="actions"><button class="go" id="ok">Publish</button></div></div></div>`;$("dlg").showModal();$("x").onclick=()=>$("dlg").close();$("ok").onclick=()=>{const city=$("lc").value||state.city;const [lat,lng]=CITIES[city]||CITIES[state.city]||[41.08,-81.52];const p={id:"mine-"+Date.now(),city,intent:state.intent,type:$("lt").value,beds:+$("lb").value,baths:+$("lba").value,sqft:+$("ls").value,price:+$("lp").value,pets:true,hood:$("lh").value,img:IMG(4),deposit:state.intent==="buy"?Math.round(+$("lp").value*0.03):+$("lp").value,title:$("ln").value,amenities:["Listed by you"],manager:state.profile.name,lease:state.intent==="buy"?"For sale":"12-month",avail:"2026-10-15",desc:"Listed by you on BrassPad.",lat,lng,med:+$("lp").value,score:80};const listed=allUserPads();listed.unshift(p);store.set("listed",listed);addInbox({title:"Listing live",body:`${p.title} in ${p.city}`,padId:p.id,kind:"list"});$("dlg").close();toast("Listing is live.");renderSearch();renderMe()}}
function openCalc(){$("dlg").innerHTML=`<div class="sheet"><div class="body"><button class="close" id="x">✕</button><h3>What you can afford</h3><p class="muted">Paste the salary from an Onramp opportunity, then see the housing range.</p><label>Yearly income</label><input class="field" id="ci" type="number" value="${state.profile.income}" /><label>Monthly debts</label><input class="field" id="cd" type="number" value="250" /><label>Down payment</label><input class="field" id="cdown" type="number" value="20000" /><p id="cout" style="margin-top:14px"></p><div class="actions"><a class="ghost" href="https://vesper-mu-ecru.vercel.app" target="_blank" rel="noreferrer" style="text-decoration:none">Browse reachable jobs ↗</a></div></div></div>`;$("dlg").showModal();$("x").onclick=()=>$("dlg").close();const run=()=>{const inc=+$("ci").value,debt=+$("cd").value,down=+$("cdown").value;const rentMax=Math.round((inc/12)*0.3);const buyPmt=Math.round((inc/12)*0.28-debt);const price=Math.max(0,Math.round(buyPmt*180+down));$("cout").innerHTML=`<div class="facts"><div class="fact"><b>Rent budget</b>${money(rentMax)}/mo</div><div class="fact"><b>Buy around</b>${money(price)}</div></div>`};["ci","cd","cdown"].forEach(id=>$(id).oninput=run);run()}
function openCompare(){const picks=[...state.saved].map(findPad).filter(Boolean).slice(0,3);if(picks.length<2){toast("Save at least 2 pads.");return}$("dlg").innerHTML=`<div class="sheet"><div class="body"><button class="close" id="x">✕</button><h3>Compare</h3><div class="facts">${picks.map(p=>`<div class="fact"><b>${money(p.price)} · ${p.hood}</b>${p.beds===0?"Studio":p.beds+" bd"} · ${p.sqft} ft² · ${dealLabel(p.score)} · ${p.pets?"pets":"no pets"}</div>`).join("")}</div></div></div>`;$("dlg").showModal();$("x").onclick=()=>$("dlg").close()}
function openThread(padId){const p=findPad(padId);if(!p)return;const msgs=state.inbox.filter(m=>m.padId===padId);$("dlg").innerHTML=`<div class="sheet"><div class="body"><button class="close" id="x">✕</button><h3>${p.manager}</h3><p class="muted">${p.title}</p>${msgs.slice().reverse().map(m=>`<div class="bubble me">${m.body}</div>`).join("")}<div class="bubble">Thanks — I can do a tour this week.</div><label>Reply</label><textarea id="ms"></textarea><div class="actions"><button class="go" id="send">Send</button></div></div></div>`;$("dlg").showModal();$("x").onclick=()=>$("dlg").close();$("send").onclick=()=>{addInbox({title:p.manager,body:$("ms").value||"Sounds good.",padId:p.id,kind:"msg"});$("dlg").close();toast("Reply sent.");renderInbox()}}
document.body.addEventListener("click",e=>{const tab=e.target.closest("[data-tab]");if(tab){showTab(tab.dataset.tab);return}const intent=e.target.closest("[data-intent]");if(intent){state.intent=intent.dataset.intent;document.querySelectorAll("[data-intent]").forEach(b=>b.classList.toggle("on",b===intent));state.max=state.intent==="buy"?800000:8000;$("maxRent").max=state.intent==="buy"?900000:8000;$("maxRent").value=$("maxRent").max;$("maxLbl").textContent="any";if(state.tab==="map")renderMap();else renderSearch();return}const save=e.target.closest("[data-save]");if(save){e.stopPropagation();const id=save.dataset.save;state.saved.has(id)?state.saved.delete(id):state.saved.add(id);persistSaved();renderSearch();if(state.tab==="saved")renderSaved();return}const city=e.target.closest("[data-city]");if(city){state.city=city.dataset.city;$("q").value=state.city;document.querySelectorAll("[data-city]").forEach(b=>b.classList.toggle("on",b.dataset.city===state.city));renderSearch();if(state.tab==="map")renderMap();return}const type=e.target.closest("[data-type]");if(type){state.type=type.dataset.type;document.querySelectorAll("[data-type]").forEach(b=>b.classList.toggle("on",b===type));renderSearch();return}const beds=e.target.closest("[data-beds]");if(beds){state.beds=beds.dataset.beds;document.querySelectorAll("[data-beds]").forEach(b=>b.classList.toggle("on",b===beds));renderSearch();return}const pets=e.target.closest("[data-pets]");if(pets){state.pets=!state.pets;pets.classList.toggle("on",state.pets);renderSearch();return}const card=e.target.closest(".card,[data-id]");if(card&&card.dataset.id&&!e.target.closest("[data-save]"))openPad(card.dataset.id);const thread=e.target.closest("[data-thread]");if(thread&&thread.dataset.thread)openThread(thread.dataset.thread)});
$("searchBtn").onclick=()=>{const v=$("q").value.trim();const names=Object.keys(CITIES);state.city=names.find(c=>c.toLowerCase()===v.toLowerCase())||names.find(c=>c.toLowerCase().startsWith(v.toLowerCase()))||v;if(!CITIES[state.city])CITIES[state.city]=CITIES["Akron, OH"];showTab("search");renderSearch()};
$("q").addEventListener("keydown",e=>{if(e.key==="Enter")$("searchBtn").click()});
$("maxRent").oninput=()=>{state.max=+$("maxRent").value;const cap=+$("maxRent").max;$("maxLbl").textContent=state.max>=cap?"any":money(state.max);renderSearch()};
$("sort").onchange=()=>{state.sort=$("sort").value;renderSearch()};
$("compareBtn").onclick=openCompare;
$("listBtn").onclick=openList;
$("calcBtn").onclick=openCalc;
document.addEventListener("keydown",e=>{if(e.key==="/"&&!["INPUT","TEXTAREA"].includes(document.activeElement.tagName)){e.preventDefault();$("q").focus()}});
document.addEventListener("click",e=>{const popBtn=e.target.closest(".leaflet-popup-content button");if(popBtn&&popBtn.dataset.id)openPad(popBtn.dataset.id)});
renderSearch();
